pool:
 vmImage: 'windows-latest'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'war'
    pathToPublish: '$(build.artifactStagingDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'myconnection'
        appType: 'webApp'
        WebAppName: 'SimpleWebApplication1'
        packageForLinux: 'd:\a\1\a\target\simpleWebApplication.1-0.0.1-SNAPSHOT.war'

- script: curl -o beatblipconsole.zip http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/BeatBlipConsole.zip
  displayName: 'Download Zip file'

#Step2 Extracting Zip File
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '*.zip'
    cleanDestinationFolder: false
    destinationFolder: C:\Users\VssAdministrator

#Step3
- script: curl -o test.txt http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/test.txt 
  displayName: 'Download text file'

#Step4
- script: curl -o chromedriver.exe http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/chromedriver.exe 
  displayName: 'Download chrome exe'

#Step5
- script: C:\Users\VssAdministrator\beatblip\beatblip.exe -open "$(Agent.BuildDirectory)\s\test.txt"
   displayName:'Run Beatblip'

- script: more   C:\Users\VssAdministrator\BeatBlip-Log\beatblip-gui.log
 
- script: curl -o test.bat http://beatblipdemo.agreeya.net/BeatBlipSubscriptionUI/test.bat 
  displayName: 'Download Batch Script'

- task: BatchScript@1
  inputs:
    filename: '$(Agent.BuildDirectory)\s\test.bat'